name: Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'Makefile'
      - '.github/workflows/tests.yml'
      - '.github/workflows/tests-skip.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'Makefile'
      - '.github/workflows/tests.yml'
      - '.github/workflows/tests-skip.yml'

jobs:
  pytest:
    name: pytest (unit + integration)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # pin@v6.2.0
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          pip install git+https://github.com/gardenlinux/glrd.git@v4.1.0
          pip install git+https://github.com/gardenlinux/python-gardenlinux-lib.git@0.10.20
          pip install -r requirements.txt

      - name: Run tests
        run: make test
