name: Inclusive Language Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  woke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # pin@v6.2.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          go install github.com/get-woke/woke@latest
          pnpm install
          pip install git+https://github.com/gardenlinux/glrd.git@v4.1.0
          pip install git+https://github.com/gardenlinux/python-gardenlinux-lib.git@0.10.20
          pip install -r requirements.txt

      - name: Run aggregate
        run: |
          make aggregate

      - name: Run inclusive language check
        run: |
          export PATH=$PATH:$HOME/go/bin
          make woke
